services:
  petproject:
    image: pp:ppapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./PetProject/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DB=Server=postgresdb;Port=5432;Database=PPDataBase;User Id=postgres;Password=passsupersafe;
    depends_on:
      - postgresdb

  clientapp:
    image: pp:clientapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./clientapp/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - petproject

  postgresdb:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: passsupersafe
      POSTGRES_USER: postgres
      POSTGRES_DB: PPDataBase
volumes:
  postgresdb-data: